### ISSUE TITLE
Investigate how to dispose of garbage

### ISSUE THREAD

**Issue by Fgerthoffert** [Gerthoffert/toronto-home#16]
http://www.homeadvisor.com/cost/cleaning-services/remove-waste/

Autre idee: annonce sur kijiji pour Free Pick Up

**Comment by Fgerthoffert** [comment]
http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=672d433112b02410VgnVCM10000071d60f89RCRD

_Closest location:_
400 Commissioners St. 
Toronto, ON M4M 3K2
**Hours** Mon. - Fri.: 6 a.m. - 6 p.m.
**Price** $11 per 100kg

**Comment by pgerthoffert** [comment]
http://www.homeadvisor.com/cost/cleaning-services/remove-waste/

Autre idee: annonce sur kijiji pour Free Pick Up

**Comment by Fgerthoffert** [comment]
We can close this one, since we have 2 possible solutions.
