### ISSUE TITLE
Design laundry

### ISSUE THREAD

**Issue by Fgerthoffert** [Gerthoffert/toronto-home#9]
Some ideas:
 - http://www.woohome.com/wp-content/uploads/2013/08/Ideas-To-Hide-A-Laundry-Room-12.jpg
 - http://blog.sweeten.com/wp-content/uploads/2015/03/SWEETEN_UES-23.jpg
 - https://st.hzcdn.com/simgs/31e14f980cde73cb_8-8147/contemporary-kitchen.jpg

**Comment by pgerthoffert** [comment]
<img width="880" alt="screen shot 2017-04-25 at 11 05 17 pm" src="https://cloud.githubusercontent.com/assets/27841251/25416405/aeeeeacc-2a0b-11e7-9fac-d6382bf04043.png">
